query ArchiveBySlug($slug: String) {
	archives(filter: { slug: { _eq: $slug } }) {
		title
		audio {
			id
		}
		curatorial_text
		about
		items {
			id
			title
			description
			palette
			image {
				id
			}
		}
	}
}
