---
name: 'deploy cms'

# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - 'cms/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: ${{ secrests.DOKKU_CMS_ENDPOINT }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
