---
name: 'deploy site'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    paths:
      - 'site/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          branch: main
          git_remote_url: ${{ secrets.DOKKU_SITE_ENDPOINT }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
